// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewnhtcgrxlptcngpmwiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3bmh0Y2dyeGxwdGNuZ3Btd2l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDA2NTQsImV4cCI6MjA3MTcxNjY1NH0.nc2q7WNr6menlT1IBn2JRcrqlTdttPU_NinUNJ1_NJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});